use_frameworks!

platform :ios, '8.0'

target 'MinewESLSingleKit_Example' do
  pod 'MinewESLSingleKit', :path => '../'

  target 'MinewESLSingleKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
